# Generated by Django 4.2.5 on 2024-04-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("heroes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcases",
                        to="heroes.heroes",
                    ),
                ),
            ],
        ),
    ]
