# Generated by Django 5.0.3 on 2024-03-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("character", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("sku", models.IntegerField(unique=True)),
                ("upc", models.CharField(max_length=100)),
                ("prototype", models.BooleanField(default=False)),
                ("edition", models.CharField(blank=True, max_length=100, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("material", models.CharField(blank=True, max_length=100, null=True)),
                ("age_rating", models.CharField(blank=True, max_length=100, null=True)),
                ("license", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("availability_status", models.CharField(max_length=100)),
                ("popularity", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("years_in_business", models.IntegerField()),
                (
                    "customer_rating",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("is_thumbnail", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.vendor"
            ),
        ),
    ]
